# Generated by Django 3.0.1 on 2019-12-28 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Raw_Material',
            fields=[
                ('r_id', models.IntegerField(primary_key=True, serialize=False)),
                ('r_name', models.CharField(max_length=10)),
                ('r_amount', models.IntegerField()),
                ('r_saveamount', models.IntegerField()),
            ],
        ),
    ]
