# Generated by Django 3.0.1 on 2020-01-01 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='addMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('add_blacktea', models.IntegerField(default=0)),
                ('add_milk', models.IntegerField(default=0)),
                ('add_pearl', models.IntegerField(default=0)),
                ('add_taro', models.IntegerField(default=0)),
                ('add_honey', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DailyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('sell_pd1', models.IntegerField(default=0)),
                ('sell_pd2', models.IntegerField(default=0)),
                ('sell_pd3', models.IntegerField(default=0)),
                ('sell_pd4', models.IntegerField(default=0)),
                ('sell_pd5', models.IntegerField(default=0)),
            ],
        ),
    ]
