# Generated by Django 3.0.1 on 2020-01-01 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_addmaterial_dailyrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raw_material',
            old_name='r_amount',
            new_name='m_left_amount',
        ),
        migrations.RenameField(
            model_name='raw_material',
            old_name='r_name',
            new_name='m_name',
        ),
        migrations.RenameField(
            model_name='raw_material',
            old_name='r_id',
            new_name='m_number',
        ),
        migrations.RenameField(
            model_name='raw_material',
            old_name='r_saveamount',
            new_name='m_safe_inventory',
        ),
    ]
