# Generated by Django 3.0.1 on 2019-12-29 20:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=11)),
                ('c_ID', models.IntegerField()),
                ('c_sex', models.IntegerField()),
                ('c_point', models.IntegerField(default=0)),
                ('c_birth', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_num', models.IntegerField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=20)),
                ('item_price', models.DecimalField(decimal_places=0, max_digits=3)),
                ('item_sales', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PurRecord',
            fields=[
                ('trade_num', models.IntegerField(primary_key=True, serialize=False)),
                ('buy_amount', models.IntegerField(default=0)),
                ('buy_total', models.IntegerField()),
                ('pur_time', models.CharField(max_length=12)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.Customer')),
                ('item_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.Item')),
            ],
        ),
    ]
