# Generated by Django 3.0.1 on 2019-12-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purrecord',
            name='pur_time',
            field=models.CharField(max_length=7),
        ),
    ]
