# Generated by Django 3.0.1 on 2019-12-31 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_auto_20191231_0124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='id',
        ),
        migrations.AlterField(
            model_name='customer',
            name='c_ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
